Feature/loop 871 share with a friend 05 2021
itk-dev/os2loop pull request #53
Opened 2021-05-06 12:29 UTC by sinejespersen

https://jira.itkdev.dk/browse/LOOP-871

2021-05-06 19:13 UTC, rimi-itk requested changes

2021-05-06 19:13 UTC, rimi-itk commented on web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/os2loop_share_with_a_friend.routing.yml
> +  path: '/node/{node}/share_with_a_friend_form'
Consider removing `_form`from the path.

2021-05-07 10:04 UTC, rimi-itk requested changes

2021-05-07 10:11 UTC, rimi-itk requested changes

2021-05-07 10:11 UTC, rimi-itk commented on web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/src/Form/ShareWithAFriendForm.php
> +    $form['submit'] = [
We should still have `$form['actions']`, but it should come last, i.e.

```
$form['title'] = …
…
$form['actions']['#type'] = 'actions';
…
```

2021-05-07 10:11 UTC, rimi-itk commented on web/profiles/custom/os2loop/modules/os2loop_share_with_a_friend/src/Form/ShareWithAFriendForm.php
> +      $this->messenger->addError($this->t('There was a problem sending your message and it was not sent.'), 'error');
Remove `, 'error'`. And if you ever need to pass the message type, use one of the constants in https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Messenger%21MessengerInterface.php/interface/MessengerInterface/9.2.x.

2021-05-19 18:36 UTC, martinyde approved these changes

2021-05-20 07:24 UTC, merged